openapi: 3.0.0
info:
  title: FlightX API
  description: An API definition for the FlightX database
  version: 1.0.0
servers:
- url: http://localhost:8080/v1
paths:
  /IndexTrackerQuery/GetAllTrackers:
    get:
      description: Get a List of all trackers
      operationId: indexTrackerQueryGetAllTrackersGET
      responses:
        "200":
          description: A List of all trackers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IndexTracker'
                x-content-type: application/json
        "400":
          description: Bad request
      x-swagger-router-controller: Default
  /IndexTrackerQuery/GetTrackerChartData:
      get:
        tags:
        - "Tracker Chart Data"
        summary: "Get the chart data for a tracker"
        description: ""
        operationId: "indexTrackerQueryGetChartDataGET"
        parameters:
        - in: "query"
          name: "ID"
          description: "The Tracker ID"
          required: true
          schema:
             type: string
        responses:
            '200':
                description: "Successful operation"
                content:
                   application/json:
                      schema:
                        type: "array"
                        items:
                          $ref: "#/components/schemas/TrackerChartDataDto"
            '401':
               description: Unauthorized
            '403':
               description: Forbidden
        x-swagger-router-controller: Default
components:
    schemas:
      IndexTracker:
        type: array
        items:                       
           type: object
           properties:
                 composition: 
                    type: array
                    items:
                       type: object
                       properties:
                          percentage:
                             type: number
                          cryptoValue:
                             type: number
                          valueFiat:
                             type: number
                          exchangeRate:
                             type: number   
                          exchangeRecordId:
                             type: string
                          symbol:
                             type: string   
                          dateAdded:
                             type: string
                          exchangeDate:
                             type: string  
                 id:
                    type: string
                 trackerId:
                    type: string
                 code:
                    type: string   
                 shortDescription:
                    type: string
                 description:
                    type: string
                 trackerCurrency:
                    type: string  
                 dateEstablished:
                    type: string
                 lastUpdate:
                    type: string
           xml:
              name: IndexTracker
      TrackerChartDataDto:
         type: array
         items:
            type: object
            properties:
               trackerId:
                  type: string
               trackerName:
                  type: string
               values:
                  type: array
                  items: 
                      type: number
               movement:
                  type: number
               period:
                  type: number
               currentValue:
                  type: number
               lastUpdateDate:
                  type: string