openapi: "3.0.0"
info:
  description: "This is the FlightX API."
  version: "1.0.0"
  title: "FlightX API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "tomas@xpsolutions.com.au"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: http://localhost:8080/
# Basic Authtication
paths:
   /IndexTrackerQuery/GetAllTrackers:
      get:
         description: Get a List of all trackers
         responses:
            '200':
                description: "Successful operation"
                content:
                   applicaton/json:
                      schema:
                        type: "array"
                        items:
                           $ref: "#/components/schemas/IndexTracker"
            '401':
               description: Unauthorized
            '403':
               description: Forbidden
         operationId: indexTrackerQueryGetAllTrackersGET

   /IndexTrackerQuery/GetTrackerChartData:
      post:
        tags:
        - "Tracker Chart Data"
        summary: "Get the chart data for a tracker"
        description: "Get Chart data"
        parameters:
        - in: "query"
          name: "ID"
          description: "The Tracker ID"
          required: true
          schema:
             type: number
        responses:
            '200':
                description: "Successful operation"
                content:
                   application/json:
                      schema:
                        type: "array"
                        items:
                          $ref: "#/components/schemas/TrackerChartDataDto"
            '401':
               description: Unauthorized
            '403':
               description: Forbidden
        operationId: GetChartData
components:
   schemas:
      IndexTracker:
        type: array
        items:                       
           type: object
           properties:
                 composition: 
                    type: array
                    items:
                       type: object
                       properties:
                          percentage:
                             type: number
                          cryptoValue:
                             type: number
                          valueFiat:
                             type: number
                          exchangeRate:
                             type: number   
                          exchangeRecordId:
                             type: string
                          symbol:
                             type: string   
                          dateAdded:
                             type: string
                          exchangeDate:
                             type: string  
                 id:
                    type: string
                 trackerId:
                    type: string
                 code:
                    type: string   
                 shortDescription:
                    type: string
                 description:
                    type: string
                 trackerCurrency:
                    type: string  
                 dateEstablished:
                    type: string
                 lastUpdate:
                    type: string
           xml:
              name: IndexTracker
      TrackerChartDataDto:
         type: array
         items:
            type: object
            properties:
               trackerId:
                  type: string
               trackerName:
                  type: string
               values:
                  type: array
                  items: 
                      type: number
               movement:
                  type: number
               period:
                  type: number
               currentValue:
                  type: number
               lastUpdateDate:
                  type: string


